# Generated by Django 5.0.6 on 2024-07-19 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_custompermission_role_customrole_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
