# Generated by Django 5.0.6 on 2024-07-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_signup_repeatpassword_alter_signup_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
