# Generated by Django 5.0.6 on 2024-07-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_facebook_profile_twitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
