# Generated by Django 5.0.6 on 2024-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_facebook_remove_profile_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
